import type { Topic } from './topics';

export const SEED_TOPICS_B: Topic[] = [
  {
    id: 'tm-parkinsons',
    title: "Parkinson's law",
    category: 'Time Management',
    prompts: [
      'Where has your work expanded to fill your day?',
      'What changed when you cut a deadline in half?',
      'Is Parkinson mostly about honesty with yourself?',
    ],
    closer: 'Which task this week would have taken half the time under pressure?',
  },
  {
    id: 'tm-deep-work',
    title: 'Deep work',
    category: 'Time Management',
    prompts: [
      'How long can you actually focus before the mind walks off?',
      'What environment lets you reach depth, and what breaks it?',
      'Is depth a skill or a mood?',
    ],
    closer: 'When did you last lose two hours in flow — what were you doing?',
  },
  {
    id: 'tm-saying-no',
    title: 'Saying no',
    category: 'Time Management',
    prompts: [
      'What did your last "yes" cost you in hours?',
      'Why do refusals feel like relationship damage?',
      'What is your script for a clean no?',
    ],
    closer: 'What are you currently saying yes to that you resent?',
  },
  {
    id: 'tm-energy',
    title: 'Energy vs time',
    category: 'Time Management',
    prompts: [
      'Are your hours equal — when is an hour worth three?',
      'How do you schedule around your worst energy instead of fighting it?',
      'What drains you fastest, and what refills you?',
    ],
    closer: 'What time of day is your sharpest — and where does it go?',
  },
  {
    id: 'tm-batching',
    title: 'Batching',
    category: 'Time Management',
    prompts: [
      'Which errand or task shrinks when done in packs?',
      'What gets worse when batched?',
      'How do you protect batch days from interruptions?',
    ],
    closer: 'What single task do you repeat one at a time that deserves a batch?',
  },
  {
    id: 'tm-audit',
    title: 'Time audit',
    category: 'Time Management',
    prompts: [
      'If you tracked every hour for a week, what would embarrass you?',
      'Which activity takes more time than it is worth?',
      'What would you stop if you saw the true ledger?',
    ],
    closer: 'Where did last weekend actually go?',
  },
  {
    id: 'tm-procrastination',
    title: "Procrastination's causes",
    category: 'Time Management',
    prompts: [
      'Is procrastination laziness, fear, or boredom?',
      'What task do you keep moving to tomorrow — and what emotion sits under it?',
      'What trick breaks the first five minutes?',
    ],
    closer: 'What are you avoiding right now by being busy?',
  },
  {
    id: 'tm-rest',
    title: 'Rest as productivity',
    category: 'Time Management',
    prompts: [
      'Can rest be scheduled without becoming another job?',
      'Why do some people recharge alone and others in company?',
      'What rest actually restores you versus just numbs you?',
    ],
    closer: 'When did you last stop with nothing queued?',
  },
  {
    id: 'tm-8020',
    title: 'The 80/20 rule',
    category: 'Time Management',
    prompts: [
      'Which 20% of your effort produces most of your results?',
      'Where does the other 80% hide — meetings, perfection, habit?',
      'What would you delete if only outcomes counted?',
    ],
    closer: 'What are you doing at 40% value that you could cut?',
  },
  {
    id: 'tm-week',
    title: 'Where the week actually goes',
    category: 'Time Management',
    prompts: [
      'If the week were money, where did you spend it?',
      'What got time it did not deserve?',
      'What earned too little of it?',
    ],
    closer: 'Rebuild next week from what mattered — what stays?',
  },
  {
    id: 'phil-stoicism',
    title: 'Stoicism today',
    category: 'Philosophy',
    prompts: [
      'What is within your control today, plainly?',
      'Does "accept what you cannot change" breed passivity or peace?',
      'Which stoic habit survives modern life intact?',
    ],
    closer: 'What did you accept recently that you used to fight?',
  },
  {
    id: 'phil-success',
    title: 'Success redefined',
    category: 'Philosophy',
    prompts: [
      'Who wrote your definition of success — and would you still sign it?',
      'What does success look like with an empty audience?',
      'At the end, which scoreboard matters?',
    ],
    closer: 'What would you do if success were invisible?',
  },
  {
    id: 'phil-free-will',
    title: 'Free will',
    category: 'Philosophy',
    prompts: [
      'If your choices come from prior causes, what is a choice?',
      'Does believing in free will change how you treat people?',
      'Where do you feel freedom in your body?',
    ],
    closer: 'Name a decision that was truly yours against every pressure.',
  },
  {
    id: 'phil-happiness',
    title: 'Happiness vs pleasure',
    category: 'Philosophy',
    prompts: [
      'Which happiness of yours has no pleasure in it?',
      'Why do intense pleasures leave so little behind?',
      'Is happiness a feeling or a direction?',
    ],
    closer: 'What pleasant thing do you keep choosing that leaves you empty?',
  },
  {
    id: 'phil-lying',
    title: 'The ethics of lying',
    category: 'Philosophy',
    prompts: [
      'Is a kind lie still a lie — and does that matter?',
      'What lies does society run on by default?',
      'Could you live a fully honest week?',
    ],
    closer: 'What is the last lie you told — and why that one?',
  },
  {
    id: 'phil-minimalism',
    title: 'Minimalism',
    category: 'Philosophy',
    prompts: [
      'What object would you keep in an empty room?',
      'Does owning less free you or just deprive you?',
      'What is the difference between minimalism and aesthetics?',
    ],
    closer: 'What did you buy that you now wish you had not?',
  },
  {
    id: 'phil-legacy',
    title: 'Legacy',
    category: 'Philosophy',
    prompts: [
      'What do you want people to say when you are not in the room?',
      'Is legacy built or accidental?',
      'What are you building that outlasts you?',
    ],
    closer: 'What part of you will exist in ten years, inside other people?',
  },
  {
    id: 'phil-time-currency',
    title: 'Time as currency',
    category: 'Philosophy',
    prompts: [
      'How do you spend a free hour — is that your real price list?',
      'Why is time harder to earn back than money?',
      'What do you sell your time for cheaply?',
    ],
    closer: 'What would you pay real money to have more time for?',
  },
  {
    id: 'phil-regret',
    title: 'Regret minimization',
    category: 'Philosophy',
    prompts: [
      'At 80, which current fear will look silly?',
      'What do people regret most — actions or inactions?',
      'How do you decide what to risk before the verdict is in?',
    ],
    closer: 'What are you not doing because you might fail?',
  },
  {
    id: 'phil-good-day',
    title: 'What a good day is',
    category: 'Philosophy',
    prompts: [
      'Strip the status and the to-do list — what makes a day good?',
      'Can a hard day still be good?',
      'What ingredients does your good day need daily?',
    ],
    closer: 'Was yesterday good — honestly?',
  },
  {
    id: 'sys-feedback',
    title: 'Feedback loops',
    category: 'Systems',
    prompts: [
      'Give an example where a small signal grew itself.',
      'Why do correction loops overshoot?',
      'Where in your life is a loop working for or against you?',
    ],
    closer: 'What habit of yours is half of a loop you never finished designing?',
  },
  {
    id: 'sys-compounding',
    title: 'Compounding',
    category: 'Systems',
    prompts: [
      'Where does a boring 1% show up later?',
      'What compounding is working against you right now?',
      'Why is the curve invisible before it is obvious?',
    ],
    closer: 'What small deposit are you making daily that future-you collects?',
  },
  {
    id: 'sys-second-order',
    title: 'Second-order thinking',
    category: 'Systems',
    prompts: [
      'What happens after the obvious fix?',
      'Give a policy that solved problem one and created problem two.',
      'How do you catch yourself at first-order thinking?',
    ],
    closer: 'What convenient solution in your life has a hidden bill?',
  },
  {
    id: 'sys-bottlenecks',
    title: 'Bottlenecks',
    category: 'Systems',
    prompts: [
      'What is the slowest stage of the thing you most care about?',
      'Does fixing a bottleneck just move it?',
      'How do you find the real constraint versus the loud one?',
    ],
    closer: 'Where are you waiting on one person or one machine?',
  },
  {
    id: 'sys-leverage-points',
    title: 'Leverage points',
    category: 'Systems',
    prompts: [
      'Where is the smallest push that moves the most?',
      'Why do we push at the loud ends instead of the leverage?',
      'Name a personal leverage point — sleep, mood, one relationship.',
    ],
    closer: 'What one change would cascade through your week?',
  },
  {
    id: 'sys-habits-systems',
    title: 'Habits vs systems',
    category: 'Systems',
    prompts: [
      'Which of your wins came from motivation — which from setup?',
      'Why do systems survive bad days when willpower does not?',
      'What system have you built on purpose?',
    ],
    closer: 'What do you rely on discipline for that should be automatic?',
  },
  {
    id: 'sys-metrics',
    title: 'Metrics that lie',
    category: 'Systems',
    prompts: [
      'Which number at work gets gamed the moment it matters?',
      'What happens when a measure becomes a target?',
      'What unmeasured thing matters most where you work?',
    ],
    closer: 'What are you optimizing that does not equal the goal?',
  },
  {
    id: 'sys-flywheels',
    title: 'Flywheels',
    category: 'Systems',
    prompts: [
      'What slow start later runs itself?',
      'How do you know a flywheel from a treadmill?',
      'Which wheel in your life needs the first hard push?',
    ],
    closer: 'What heavy thing became easy once it was moving?',
  },
  {
    id: 'sys-chestertons-fence',
    title: "Chesterton's fence",
    category: 'Systems',
    prompts: [
      'Why is "remove it, it is useless" often wrong?',
      'When did understanding a rule change whether you kept it?',
      'What tradition did you keep after learning its reason?',
    ],
    closer: 'What fence are you tempted to tear down without reading the plan?',
  },
  {
    id: 'sys-constraints',
    title: 'Constraints as teachers',
    category: 'Systems',
    prompts: [
      'Which limit made your best work?',
      'Do you work better with a wall or with open space?',
      'What did a hard budget or deadline force you to invent?',
    ],
    closer: 'What constraint would you add on purpose?',
  },
  {
    id: 'gen-money-happiness',
    title: 'Money and happiness',
    category: 'General',
    prompts: [
      'At what income does more money stop adding joy — for you?',
      'What did money buy you that actually lasted?',
      'What broke in your life when money was tight?',
    ],
    closer: 'What would money not fix about your current days?',
  },
  {
    id: 'gen-best-decision',
    title: 'Best decision ever',
    category: 'General',
    prompts: [
      'Walk through your best decision — luck, skill, or both?',
      'How did you recognize it at the time?',
      'What did it cost to choose it?',
    ],
    closer: 'What decision are you still paying for — happily or not?',
  },
  {
    id: 'gen-childhood',
    title: 'Childhood lessons',
    category: 'General',
    prompts: [
      'Which rule from childhood still runs your adult life?',
      'What did your parents teach by example rather than words?',
      'What lesson took you twenty years to unlearn?',
    ],
    closer: 'What are you teaching kids around you without saying it?',
  },
  {
    id: 'gen-fear-risk',
    title: 'Fear and risk',
    category: 'General',
    prompts: [
      'What are you actually afraid of inside the risk you take?',
      'When did fear protect you versus shrink you?',
      'Describe a risk that paid in lessons even when it lost money.',
    ],
    closer: 'What fear would you walk at today if nobody watched?',
  },
  {
    id: 'gen-skills',
    title: 'Skills worth learning',
    category: 'General',
    prompts: [
      'Which skill pays back every month after you own it?',
      'What did you learn late and wish earlier?',
      'What are you refusing to learn out of pride?',
    ],
    closer: 'If you had a free year, what would you learn first?',
  },
  {
    id: 'gen-five-year',
    title: 'Five-year ambitions',
    category: 'General',
    prompts: [
      'Picture five years ahead — what is true if it worked?',
      'Which ambitions are yours and which are borrowed?',
      'What must be true this year for that picture to stand?',
    ],
    closer: 'What will you start this month toward it?',
  },
  {
    id: 'gen-ego',
    title: 'Ego',
    category: 'General',
    prompts: [
      'What does your ego protect that might survive exposure?',
      'When did pride cost you more than the thing itself?',
      'How does ego show up in your work and your fights?',
    ],
    closer: 'What praise do you secretly need most?',
  },
  {
    id: 'gen-comparison',
    title: 'Comparison',
    category: 'General',
    prompts: [
      'Whose life do you measure yours against — and why that person?',
      'What does envy tell you that criticism hides?',
      'How do you step off the ladder?',
    ],
    closer: 'Who would you stop comparing to today?',
  },
  {
    id: 'gen-boredom',
    title: 'Boredom',
    category: 'General',
    prompts: [
      'What happens when you sit for ten minutes with nothing?',
      'Is boredom a problem or a doorway?',
      'When did boredom last produce something good for you?',
    ],
    closer: 'When did you last be bored on purpose?',
  },
  {
    id: 'gen-gratitude',
    title: 'Gratitude vs ingratitude',
    category: 'General',
    prompts: [
      'What do you have that past-you begged for?',
      'Why does the good become invisible once it is normal?',
      'What is the difference between gratitude and debt?',
    ],
    closer: 'Name one ordinary thing you would genuinely miss tomorrow.',
  },
  {
    id: 'st-first-money',
    title: 'First money earned',
    category: 'Stories',
    prompts: [
      'Tell the story of the first money you earned yourself — every scene.',
      'What did that money mean beyond the amount?',
      'Who did you want to impress with it?',
    ],
    closer: 'How did that first earner turn out — the kid in the story?',
  },
  {
    id: 'st-got-away',
    title: 'A time you got away with something',
    category: 'Stories',
    prompts: [
      'Full story: the plan, the moment of near-catch, the escape.',
      'What did you feel right after — pride or itch?',
      'Did it change what you would do next time?',
    ],
    closer: 'What did that story teach you about rules?',
  },
  {
    id: 'st-worst-decision',
    title: 'Worst decision and its lesson',
    category: 'Stories',
    prompts: [
      'Tell the worst decision like a film — before, choice, aftermath.',
      'What sign did you ignore?',
      'What would the same you tell that you now?',
    ],
    closer: 'What did that decision secretly make possible later?',
  },
  {
    id: 'st-embarrassing',
    title: 'Most embarrassing moment',
    category: 'Stories',
    prompts: [
      'Set the scene: where, who, the exact moment of collapse.',
      'What saved you — time, humor, someone?',
      'Does it still sting, or is it a trophy now?',
    ],
    closer: 'What did surviving it prove about you?',
  },
  {
    id: 'st-changed-path',
    title: 'A person who changed your path',
    category: 'Stories',
    prompts: [
      'Who was the person, the moment, the sentence they said?',
      'What path were you on before them?',
      'Would you be sitting here different without them?',
    ],
    closer: 'What do you owe that person still?',
  },
  {
    id: 'st-lost',
    title: 'A time you were lost',
    category: 'Stories',
    prompts: [
      'Physical or metaphorical — tell the lost time in detail.',
      'What did you do in the first ten minutes of panic?',
      'What did being lost teach that maps never could?',
    ],
    closer: 'Where are you a little lost right now?',
  },
  {
    id: 'st-funniest-day',
    title: 'The funniest day',
    category: 'Stories',
    prompts: [
      'Tell it beat by beat — what made it escalate?',
      'Who was there, and who laughed hardest?',
      'Why does that day still surface at the right moment?',
    ],
    closer: 'What ordinary day went quietly hilarious in memory?',
  },
  {
    id: 'st-close-call',
    title: 'A close call',
    category: 'Stories',
    prompts: [
      'Tell the near-miss — seconds, meters, luck.',
      'What did you notice at the last moment?',
      'How close was close — and what changed after?',
    ],
    closer: 'What close call made you more careful — or did none?',
  },
  {
    id: 'st-lied-about',
    title: 'Something you lied about',
    category: 'Stories',
    prompts: [
      'Tell what you lied about, to whom, and why.',
      'How long did the lie live?',
      'What did carrying it cost — and what did confessing cost?',
    ],
    closer: 'What do lies protect — and what do they eat?',
  },
  {
    id: 'st-everything-right',
    title: 'The day everything went right',
    category: 'Stories',
    prompts: [
      'Rebuild that day hour by hour.',
      'Was it luck, preparation, or both?',
      'What tiny thing at the start made the rest fall in?',
    ],
    closer: 'What would need to align for another day like it?',
  },
];
