import type { Topic } from './topics';
import { SEED_TOPICS_B } from './seedTopics2';

const SEED_TOPICS_A: Topic[] = [
  {
    id: 'mod-attention',
    title: 'The attention economy',
    category: 'Modern',
    prompts: [
      "Who actually pays for the apps on your phone, and what do they buy with that money?",
      "When did your attention last get sold without you noticing?",
      "If attention is the scarce resource, how rich are you compared with ten years ago?",
      "What would an app look like if it respected your time?",
    ],
    closer: 'What got the most of your attention yesterday — and did you choose it?',
  },
  {
    id: 'mod-doomscroll',
    title: 'Doomscrolling',
    category: 'Modern',
    prompts: [
      'Why does bad news pull harder than good news?',
      'Describe the last time you lost 30 minutes to scrolling. What triggered it?',
      'Is doomscrolling a personal failure or a designed outcome? What would change if feeds ended after 10 minutes?',
    ],
    closer: 'What does your thumb reach for first when you are stressed?',
  },
  {
    id: 'mod-ai-judgment',
    title: 'AI and judgment',
    category: 'Modern',
    prompts: [
      "Where do you still trust your own judgment over a model's answer?",
      'When AI is confidently wrong, who pays? Name a domain where that matters.',
      'Has AI changed how you form opinions, or only how you fetch facts?',
    ],
    closer: 'What judgment do you refuse to outsource, and why that one?',
  },
  {
    id: 'mod-remote-loneliness',
    title: 'Remote-work loneliness',
    category: 'Modern',
    prompts: [
      'What does office small talk actually do for a person?',
      'Can deep work and social life share the same room? How have you solved it?',
      'What has remote work taken from you that you did not expect to miss?',
    ],
    closer: 'When did your workplace last feel like a place, not a login?',
  },
  {
    id: 'mod-cancel-culture',
    title: 'Cancel culture',
    category: 'Modern',
    prompts: [
      'Where is the line between accountability and pile-on?',
      'Should context, intent, or the age of the offense change the verdict?',
      'What happens to a society where every mistake is remembered forever?',
    ],
    closer: 'Have you ever changed your mind about someone after the crowd had spoken?',
  },
  {
    id: 'mod-hustle',
    title: 'Hustle culture',
    category: 'Modern',
    prompts: [
      'Who benefits when rest is framed as laziness?',
      'What is the difference between ambition and hustle theater?',
      'How much of "grind" is visible effort rather than real results?',
    ],
    closer: 'What would you stop performing if nobody could see your effort?',
  },
  {
    id: 'mod-dating-apps',
    title: 'Dating apps',
    category: 'Modern',
    prompts: [
      'What did dating apps change about how people treat each other?',
      'Is choice overload making people better or pickier at picking?',
      'What did people lose when meeting moved from place to profile?',
    ],
    closer: 'Why do people stay on apps that make them unhappy?',
  },
  {
    id: 'mod-echo-chambers',
    title: 'Echo chambers',
    category: 'Modern',
    prompts: [
      'How would you even notice if you lived in one?',
      'Does disagreeing with everyone in your feed mean you escaped it?',
      'Which ideas got weaker the more you only saw your own side?',
    ],
    closer: 'Which belief of yours has never met real resistance?',
  },
  {
    id: 'mod-phone-addiction',
    title: 'Phone addiction',
    category: 'Modern',
    prompts: [
      'What is the difference between using a phone and being used by it?',
      'What did you replace phone time with the one week you cut it down?',
      'Is the phone the problem, or the absence of something better to do?',
    ],
    closer: 'What is the first thing you reach for — and what feeling is underneath it?',
  },
  {
    id: 'mod-misinformation',
    title: 'Misinformation',
    category: 'Modern',
    prompts: [
      'Why does a lie finish spreading before the correction starts?',
      'What makes a source believable to you, personally?',
      'Should platforms delete falsehoods or label them — what is lost either way?',
    ],
    closer: 'When did you last share something that turned out wrong?',
  },
  {
    id: 'pw-friendships',
    title: 'Power inside friendships',
    category: 'Power',
    prompts: [
      'Who decides what you do together — and how did that happen?',
      'Can friendship survive a large gap in status or money?',
      'What does quiet power look like between two equal friends?',
    ],
    closer: 'When did you last go along with a friend just to keep peace?',
  },
  {
    id: 'pw-soft-hard',
    title: 'Soft power vs hard power',
    category: 'Power',
    prompts: [
      'When did soft power — charm, obligation — work better on you than force?',
      'Can you name a time you obeyed without anyone making you?',
      'Which kind of power do you respect more, and which do you distrust?',
    ],
    closer: 'Who in your life holds soft power over you right now?',
  },
  {
    id: 'pw-corruption',
    title: "Corruption's roots",
    category: 'Power',
    prompts: [
      'Is corruption about bad people or good systems?',
      'At what point does a small favor become a bribe?',
      'Why do clean systems rot in some places and hold in others?',
    ],
    closer: 'What would you do if the only way to get justice was to pay someone off?',
  },
  {
    id: 'pw-attention',
    title: 'Attention as power',
    category: 'Power',
    prompts: [
      'Who can command the attention of a room — and what are they doing with it?',
      'Is attention the last currency that cannot be faked?',
      'How does whoever controls your feed control your opinions?',
    ],
    closer: 'What do you do to be noticed that you privately find undignified?',
  },
  {
    id: 'pw-leverage',
    title: 'Leverage',
    category: 'Power',
    prompts: [
      'Describe a moment you had leverage and used it well — or wasted it.',
      'What makes leverage real versus imagined?',
      'Is leverage always a zero-sum game?',
    ],
    closer: 'What form of leverage would you refuse to hold?',
  },
  {
    id: 'pw-refusing',
    title: 'Refusing power',
    category: 'Power',
    prompts: [
      'Why do some people walk away from authority others chase?',
      'What does refusing power cost the person who refuses?',
      'Is stepping down ever harder than fighting to keep a position?',
    ],
    closer: 'Have you ever been handed power you were not sure you deserved?',
  },
  {
    id: 'pw-charisma-authority',
    title: 'Charisma vs authority',
    category: 'Power',
    prompts: [
      'Who follows a person because of who they are — and who because of the title?',
      'Can authority exist without charisma, or charisma without authority?',
      'Which fails faster under pressure?',
    ],
    closer: 'Which kind of leader do you actually obey?',
  },
  {
    id: 'pw-at-work',
    title: 'Power at work',
    category: 'Power',
    prompts: [
      'How does power actually flow in your workplace — org chart or hallway?',
      'Who can stop a project with one sentence, and why them?',
      'What does a powerless job do to a person over years?',
    ],
    closer: 'When did you last influence a decision without any formal authority?',
  },
  {
    id: 'pw-corrupts',
    title: 'When power corrupts',
    category: 'Power',
    prompts: [
      'Does power change people, or reveal them?',
      'What safeguards would you put on yourself if you held real power?',
      'Name a case where power stayed clean — what protected it?',
    ],
    closer: 'What part of you would change first if you had total control?',
  },
  {
    id: 'pw-your-silence',
    title: 'Who benefits from your silence',
    category: 'Power',
    prompts: [
      'If you stay quiet on one issue you care about, who gains?',
      'Why do people stay silent even when speaking is safe?',
      'What is the real price of saying the obvious out loud?',
    ],
    closer: 'What have you left unsaid that still sits with you?',
  },
  {
    id: 'mani-persuasion',
    title: 'Persuasion vs manipulation',
    category: 'Manipulation',
    prompts: [
      'Where does influence become control?',
      'Is intent the only difference — or is consent?',
      'Have you ever been persuaded and grateful, or persuaded and used?',
    ],
    closer: 'How do you tell, in the moment, which one is happening to you?',
  },
  {
    id: 'mani-gaslighting',
    title: 'Gaslighting signs',
    category: 'Manipulation',
    prompts: [
      'What does the first crack of doubt sound like when someone denies your reality?',
      'Why is it so hard to prove you were not crazy?',
      'How do you rebuild trust in your own memory after it?',
    ],
    closer: 'Have you ever doubted a memory that turned out true?',
  },
  {
    id: 'mani-ad-tricks',
    title: 'Ad tricks',
    category: 'Manipulation',
    prompts: [
      'Which ad technique actually works on you — honestly?',
      'What is the difference between an ad that informs and one that nags?',
      'How much of marketing sells the product versus selling the insecurity?',
    ],
    closer: 'Name a purchase you made because of the feeling, not the thing.',
  },
  {
    id: 'mani-emotional-blackmail',
    title: 'Emotional blackmail',
    category: 'Manipulation',
    prompts: [
      'What does "after everything I have done for you" really purchase?',
      'Why does guilt work as leverage between people who love each other?',
      'How do you refuse without detonating the relationship?',
    ],
    closer: 'When did you last say yes against your own interest to pay a guilt debt?',
  },
  {
    id: 'mani-dark-patterns',
    title: 'Dark patterns in apps',
    category: 'Manipulation',
    prompts: [
      'Which trick has cost you time or money online?',
      'Why do companies keep using them if everyone hates them?',
      'Should dark patterns be illegal — or is that unenforceable?',
    ],
    closer: 'What is the most expensive "cancel" flow you have ever fought through?',
  },
  {
    id: 'mani-detecting-lies',
    title: 'Detecting lies',
    category: 'Manipulation',
    prompts: [
      'What actually signals a lie — tone, detail, timing, or nothing?',
      'Can lie detectors beat chance, and why do we trust them anyway?',
      'When is detecting a lie less useful than asking why someone needs to lie?',
    ],
    closer: 'Think of someone who lies badly. What gives them away?',
  },
  {
    id: 'mani-fomo',
    title: 'FOMO engineering',
    category: 'Manipulation',
    prompts: [
      'Which scarcity tricks work on you — countdown timers, "only 2 left", friends-are-buying?',
      'What does FOMO protect you from feeling if you sit still?',
      'How do you create enough distance to want something on purpose?',
    ],
    closer: 'What did you buy or join because everyone else seemed to be?',
  },
  {
    id: 'mani-social-pressure',
    title: 'Social pressure',
    category: 'Manipulation',
    prompts: [
      'Describe a time you did something out of step with your values because the room wanted it.',
      'Why is the cost of standing alone so high?',
      'What small act of refusal have you seen shift a whole group?',
    ],
    closer: "Which group's opinion do you feel even when you are alone?",
  },
  {
    id: 'mani-tribal',
    title: 'Tribal loyalty',
    category: 'Manipulation',
    prompts: [
      'What makes a person defend their side when it is plainly wrong?',
      'Where is loyalty a virtue and where a leash?',
      'Have you ever left a tribe — what did it cost?',
    ],
    closer: 'What criticism of "your people" can you say out loud?',
  },
  {
    id: 'mani-cults',
    title: 'How cults recruit',
    category: 'Manipulation',
    prompts: [
      'What empty door does a cult knock on?',
      'Which normal-looking group did you watch turn controlling?',
      'Why do smart people stay after the first red flag?',
    ],
    closer: 'What keeps ordinary people in bad situations longer than they should?',
  },
  {
    id: 'gov-democracy-efficiency',
    title: 'Democracy vs efficiency',
    category: 'Government',
    prompts: [
      'When has a slow vote beat a fast decree?',
      'Can a country be both well-run and truly free?',
      'What do you give up when decisions move fast?',
    ],
    closer: 'Which do you trust more — a messy vote or a competent autocrat?',
  },
  {
    id: 'gov-anarchy',
    title: 'Is anarchy viable?',
    category: 'Government',
    prompts: [
      'What happens the day after the state disappears?',
      'Where in real life does stateless order already work?',
      'Is anarchy a destination or a warning?',
    ],
    closer: 'What is the first thing you would miss about government?',
  },
  {
    id: 'gov-taxes',
    title: 'Taxes',
    category: 'Government',
    prompts: [
      "What is a fair share when everyone's idea of fair differs?",
      'Who should pay more — and what do they owe back?',
      'At what rate does tax stop being contribution and start being seizure?',
    ],
    closer: 'What has your tax money bought that you would pay for again?',
  },
  {
    id: 'gov-censorship',
    title: 'Censorship',
    category: 'Government',
    prompts: [
      'Who should decide what a society cannot say?',
      'Does censorship protect the vulnerable or protect power?',
      'What is lost when speech is cleaned before it is heard?',
    ],
    closer: 'Which idea would you defend even if it disgusted you?',
  },
  {
    id: 'gov-term-limits',
    title: 'Term limits',
    category: 'Government',
    prompts: [
      'Do representatives serve the people or their seat?',
      'Would term limits bring fresh blood or permanent amateurs?',
      'What other job bans experience on purpose?',
    ],
    closer: 'How many terms would you give a leader you love — and one you hate?',
  },
  {
    id: 'gov-voting-systems',
    title: 'Voting systems',
    category: 'Government',
    prompts: [
      'Would your country vote differently under ranked choice, runoff, or lottery?',
      'Why do so many feel forced to choose the lesser evil?',
      'Is winning 35% of votes a mandate?',
    ],
    closer: 'Have you ever not voted because the system felt rigged?',
  },
  {
    id: 'gov-propaganda',
    title: 'Propaganda history',
    category: 'Government',
    prompts: [
      'Which old propaganda trick still works on you today?',
      'How do you recognize a state narrative while inside it?',
      'What is the difference between education and propaganda?',
    ],
    closer: 'What belief did you absorb from school that you later dropped?',
  },
  {
    id: 'gov-police-trust',
    title: 'Police trust',
    category: 'Government',
    prompts: [
      'What makes a person call the police — and what stops them?',
      'Can trust in police be rebuilt once broken, and how?',
      'What would you replace armed response with for noise, welfare, and mental health calls?',
    ],
    closer: 'When did the police last feel like help to you?',
  },
  {
    id: 'gov-foreign',
    title: 'Foreign interference',
    category: 'Government',
    prompts: [
      'Why does outside meddling find willing insiders?',
      'If another country shaped your election, what would count as proof?',
      'Where is influence exploitation and where is it just diplomacy?',
    ],
    closer: 'How much of what you believe about foreign nations did your own media choose?',
  },
  {
    id: 'gov-watchers',
    title: 'Who watches the watchers',
    category: 'Government',
    prompts: [
      'What oversight actually works when the overseers are cozy?',
      'Who audits the auditors without becoming the threat?',
      'What technology would you put on every uniform — and what would it break?',
    ],
    closer: 'Which institution in your country is least watched and most powerful?',
  },
  {
    id: 'rel-maintenance',
    title: 'Friendship maintenance',
    category: 'Relationships',
    prompts: [
      'What does a real friendship require per month?',
      'Do friendships fade from neglect or from change?',
      'Is it sad when a friendship ends, or just natural?',
    ],
    closer: 'Who would you call at 3am — and when did you last prove they could?',
  },
  {
    id: 'rel-conflict',
    title: 'Conflict resolution',
    category: 'Relationships',
    prompts: [
      'Describe a friendship that survived a real fight. What saved it?',
      'Why is the first honest sentence so hard?',
      'Is peace worth an unresolved argument?',
    ],
    closer: 'What conflict are you still carrying unfinished?',
  },
  {
    id: 'rel-money',
    title: 'Money between friends',
    category: 'Relationships',
    prompts: [
      'Should friends lend, gift, or never mix money?',
      'What is the fair way to split a bill when incomes differ?',
      'How did money quietly rewrite a friendship you had?',
    ],
    closer: 'What is the largest sum you would hand a friend without a receipt?',
  },
  {
    id: 'rel-family-boundaries',
    title: 'Family boundaries',
    category: 'Relationships',
    prompts: [
      'Where does duty to family end and self-preservation begin?',
      'Which family rule did you refuse to inherit?',
      'How do you say no to a parent without burning the bridge?',
    ],
    closer: 'What boundary do you keep defending against guilt?',
  },
  {
    id: 'rel-forgiveness',
    title: 'Forgiveness',
    category: 'Relationships',
    prompts: [
      'Is forgiveness for them, for you, or for nobody?',
      'Can you forgive without forgetting — and should you?',
      'Name a wrong you still refuse to forgive. What does holding it protect?',
    ],
    closer: 'What would change if you forgave one person today?',
  },
  {
    id: 'rel-jealousy',
    title: 'Jealousy',
    category: 'Relationships',
    prompts: [
      'Whose life triggers envy in you — and what exactly do you want from it?',
      'Is jealousy information or poison?',
      'How do you act when the green feeling arrives?',
    ],
    closer: 'What do you have that others quietly envy in you?',
  },
  {
    id: 'rel-communication',
    title: 'Communication styles',
    category: 'Relationships',
    prompts: [
      'Do you say what you mean the first time, or test the water?',
      'Who taught you your style of fighting — and is it working?',
      'What gets lost between the words you choose and the words heard?',
    ],
    closer: 'What sentence do you keep failing to say out loud?',
  },
  {
    id: 'rel-distance',
    title: 'Distance and closeness',
    category: 'Relationships',
    prompts: [
      'How much closeness can you actually stand?',
      'Has distance saved any of your relationships?',
      'Is constant contact intimacy or surveillance?',
    ],
    closer: 'Who in your life is physically near but far away?',
  },
  {
    id: 'rel-asking-help',
    title: 'Asking for help',
    category: 'Relationships',
    prompts: [
      'Why is asking harder than giving?',
      'Describe the last time you needed help and did not ask. What stopped you?',
      'What does needing people cost your self-image?',
    ],
    closer: 'Who could help you today if you sent one message?',
  },
  {
    id: 'rel-ending',
    title: 'Ending a friendship',
    category: 'Relationships',
    prompts: [
      'What does a friendship death look like — explosion or silence?',
      'Do you owe someone an explanation when you walk away?',
      'How do you grieve someone who is still alive?',
    ],
    closer: 'Which friendship have you quietly attended as a funeral?',
  },
  {
    id: 'hlth-sleep-debt',
    title: 'Sleep debt',
    category: 'Health',
    prompts: [
      'What has chronic short sleep taken from you — mood or memory first?',
      'Why is sleep the first thing sacrificed and the first thing needed?',
      'What does your sleep look like on a good week versus a bad one?',
    ],
    closer: 'What would improve first if you slept 8 hours for a month?',
  },
  {
    id: 'hlth-exercise-min',
    title: 'Exercise minimums',
    category: 'Health',
    prompts: [
      'What is the least work that keeps a body usable at 50?',
      'Why does "something beats nothing" feel like a lie on tired days?',
      'How did you learn what your actual minimum is?',
    ],
    closer: 'What can your body do now that it could not a year ago?',
  },
  {
    id: 'hlth-diet-myths',
    title: 'Diet myths',
    category: 'Health',
    prompts: [
      'Which diet belief did you hold and later abandon?',
      'Why do nutrition truths keep flipping?',
      'What role does food play beyond fuel in your life?',
    ],
    closer: 'Name one eating habit you would defend against every study.',
  },
  {
    id: 'hlth-stigma',
    title: 'Mental-health stigma',
    category: 'Health',
    prompts: [
      'Which feeling do men around you treat as forbidden?',
      'What would change if seeking help read as strength?',
      'Where does stigma still cost people jobs or respect?',
    ],
    closer: 'What is the honest temperature check of your own mind this month?',
  },
  {
    id: 'hlth-stress',
    title: 'Stress physiology',
    category: 'Health',
    prompts: [
      'Where does stress live in your body first?',
      'What does a stress response look like when there is no predator to fight?',
      'Which of your stressors are signal, which are noise?',
    ],
    closer: 'What does your body beg for when you are wound up?',
  },
  {
    id: 'hlth-posture',
    title: 'Posture',
    category: 'Health',
    prompts: [
      'What has the desk done to your frame?',
      'Does fixing posture fix pain — or is the pain deeper?',
      'What physical habits would you pass to a kid?',
    ],
    closer: 'Stand up straight right now — what changed?',
  },
  {
    id: 'hlth-hydration',
    title: 'Hydration',
    category: 'Health',
    prompts: [
      'How much of your "low energy" days started dry?',
      'What makes water hard to drink for you?',
      'Do you notice water in your mood or only in your thirst?',
    ],
    closer: 'When did you last feel genuinely thirsty?',
  },
  {
    id: 'hlth-screen-time',
    title: 'Screen time',
    category: 'Health',
    prompts: [
      'What do the hours on the screen report card actually say?',
      'Is screen time the problem, or screen content?',
      'What screen habit would you kill first?',
    ],
    closer: 'What deserves the attention your screen took today?',
  },
  {
    id: 'hlth-substance',
    title: 'Substance honesty',
    category: 'Health',
    prompts: [
      'Why is honest talk about weed or drink so loaded?',
      'What is the line between ritual and dependence?',
      'How do you judge your own use without lying to yourself?',
    ],
    closer: 'If you stopped for a month, what would you learn?',
  },
  {
    id: 'hlth-recovery',
    title: 'Recovery days',
    category: 'Health',
    prompts: [
      'Do you treat rest as part of training or as skipping it?',
      'What does true recovery look like versus collapse?',
      'When did you last stop before you were forced?',
    ],
    closer: 'Which came last time — rest or burnout?',
  },
];

export const SEED_TOPICS: Topic[] = [...SEED_TOPICS_A, ...SEED_TOPICS_B];
